import * as vscode from 'vscode';
import * as path from 'path';
import { generateTree } from './tree/generator';

export function activate(context: vscode.ExtensionContext) {
	const command = vscode.commands.registerCommand('treescope.generateFromFolder',

		async (uri: vscode.Uri) => {
			if (!uri || !uri.fsPath) {
				vscode.window.showErrorMessage('No folder selected!');
				return;
			}

			const folderPath = uri.fsPath;
			const folderName = path.basename(folderPath);
			const tree = generateTree(folderPath);

			const time = new Date().toLocaleTimeString();

			const content = ` 📂File Tree for ${folderName}
			📍 Root:${folderPath} 
			( 🕧Generated at ${time}):\n\n${tree}
			
			---
			\`\`\`
			${tree}
			\`\`\`
			
			---

generated by TreeScope - Your File System Explorer
			Created by owsam22🤘🏻
			`;

			const fileName = `${folderName}-file-tree.md`;

			const doc = await vscode.workspace.openTextDocument({ content, language: 'markdown' });
			await vscode.window.showTextDocument(doc, { preview: false });


		}
	);


	context.subscriptions.push(command);
}