import * as vscode from "vscode";
import * as path from "path";
import { generateTree } from "./tree/generator";

function createContent(folderPath: string) {
  const folderName = path.basename(folderPath);

  const { tree, fileCount, folderCount } = generateTree(folderPath);

  const time = new Date().toLocaleString();

  return `# 📁 File Tree: ${folderName}

📍 Root: ${folderPath}  
🕒 Generated: ${time}  

📊 Folders: ${folderCount} | Files: ${fileCount}

---

\`\`\`
${folderName}/
${tree}
\`\`\`

---

*Generated by TreeScope*
`;
}

export function activate(context: vscode.ExtensionContext) {

  // 👉 Right-click on folder
  const fromFolder = vscode.commands.registerCommand(
    "treescope.generateFromFolder",
    async (uri: vscode.Uri) => {
      if (!uri) {
        vscode.window.showErrorMessage("No folder selected");
        return;
      }

      const folderPath = uri.fsPath;
      const content = createContent(folderPath);

      const fileName = `File Tree - ${path.basename(folderPath)}.md`;
      const fileUri = vscode.Uri.file(path.join(folderPath, fileName));

      await vscode.workspace.fs.writeFile(
        fileUri,
        Buffer.from(content, "utf8")
      );

      await vscode.window.showTextDocument(fileUri);
    }
  );

  // 👉 Command palette (workspace root)
  const fromWorkspace = vscode.commands.registerCommand(
    "treescope.generateFromWorkspace",
    async () => {
      const folder = vscode.workspace.workspaceFolders?.[0];

      if (!folder) {
        vscode.window.showErrorMessage("No workspace found");
        return;
      }

      const folderPath = folder.uri.fsPath;
      const content = createContent(folderPath);

      const fileName = `File Tree - ${path.basename(folderPath)}.md`;
      const fileUri = vscode.Uri.file(path.join(folderPath, fileName));

      await vscode.workspace.fs.writeFile(
        fileUri,
        Buffer.from(content, "utf8")
      );

      await vscode.window.showTextDocument(fileUri);
    }
  );

  context.subscriptions.push(fromFolder, fromWorkspace);
}